log4js-node/streamroller

lib/BaseRollingFileStream.js
test/BaseRollingFileStream-test.js
test/read-only-file-test.js

This is a fix for issue #2 - where the caller could not catch an exception that happens when the underlying stream is created.

Allows checking for errors on stream creation (issue #2)

---

lib/BaseRollingFileStream.js
lib/RollingFileStream.js
package.json
test/BaseRollingFileStream-test.js
test/RollingFileStream-test.js

1) Use `mkdirp` to create the logfile directory before creating the filename. This way we can provide nested subdirectories that may not necessarily exist.
2) If the log directory has been deleted, rolling over currently throws. Instead we should handle this error gracefully and just proceed as usual.

Better handling of missing directories

---

lib/DateRollingFileStream.js
test/DateRollingFileStream-test.js

I've added a daysToKeep option to the DateRollingFileStream object. 
The setting will be used on log rollover to only keep a certain number of days of logs. It's similar to backups on the RollingFileStream object but more specifically oriented to the day based rolling of files.
I've added tests to confirm the behavior.

Days to keep

---

lib/BaseRollingFileStream.js

Current code overrides two functions:
- `_write` (called by internal streams code, and reads from internal buffer)
- `end` (called externally)
So `_write` is called whenever data is fully processed (i.e. `_write` called, then it invokes callback, only then it's called again). `end` is called straight away.
When recipient stream is slow enough, this creates a possibility that `write-write-write-end` calls will actually translate to `_write-_write-end-_write` sequence. Which creates an error because you can't write to a stream that's already closed.
Here's a demo:
```js
var fs = require('fs')
var stream = require('stream')
fs.createWriteStream = function () {
var s = new stream.Writable()
s._write = function (data,__,cb) {
setTimeout(function () {
console.log(data)
cb()
}, 1000)
}
return s …
```

"Error: write after end"

---

package-lock.json
src/RollingFileWriteStream.js
test/RollingFileWriteStream-test.js

This fixes #23 by following the node.js fs rules around relative paths - they get process.cwd() prepended.

fix: relative paths should use process.cwd

---

lib/RollingFileWriteStream.js
test/DateRollingFileStream-test.js

This was an error I found when testing some stuff in log4js. If the date pattern is something like '.yyyyMMdd', or even just '.ss' then the date rolling was identifying the date part of the filename as the index and crashing because it could not find the date part.

fix: was crashing when pattern is all digits

---

lib/RollingFileWriteStream.js
test/RollingFileWriteStream-test.js

Fix for #34 - if appending to an existing file on startup, it will now check the current size.

fix: file rolling now picks up existing file size if appending

---

lib/RollingFileWriteStream.js
test/RollingFileWriteStream-test.js

This is a fix for #36, I hope.

fix: checks existing file creation time

---

lib/RollingFileWriteStream.js
test/RollingFileStream-test.js
test/RollingFileWriteStream-test.js

This PR fixes #42 - when rolling the old code would only keep track of files it had created during the current run, ignoring old files from previous runs.
Urgh. Installed the "prettier" plugin for atom and it has decided to convert all single quote strings to double quotes, so there's a lot of noise in the diffs below.

fix: pick up existing backups

---

lib/RollingFileWriteStream.js
lib/fileNameFormatter.js
lib/fileNameParser.js
package.json
test/fileNameFormatter-test.js
test/fileNameParser-test.js

I've replaced `_formatFileName` and `_parseFileName` with two new functions loaded from different modules. I think it makes the code easier to understand (and also should fix a bug where you could get errors if files existed that had dates which could not be parsed in them).

Simplifying some of the more complicated functions

---

lib/RollingFileWriteStream.js
lib/fileNameParser.js
package.json
test/RollingFileWriteStream-test.js

To reduce amount of non critical dependencies given that readability and expressiveness is comparable.
I just noticed that this PR conflicts a bit with https://github.com/log4js-node/streamroller/tree/simplify branch. I can rebase it once `simplify` is merged.
It also looks like it will be rather easy to eliminate `async` from production dependencies.
What do you think about these changes?

refactor: replace lodash helpers with native alternatives

---

lib/fileNameParser.js
test/fileNameParser-test.js

See https://github.com/log4js-node/streamroller/pull/45#issuecomment-515999445 for the reasoning behind the change.

fix: fix date parsing and made tests not timezone sensitive

---

lib/RollingFileWriteStream.js
package.json

Inspired by PR #45 (thanks @devoto13 ) - I've removed the async library from the main code. It is still used in the tests, so it's now moved to a dev dependency. I took the opportunity to use async/await now that we don't have to support node v6.

refactor: moved async to dev-only dependency

---

lib/RollingFileWriteStream.js
test/RollingFileWriteStream-test.js

The code that looks up the existing file size and timestamp was only checking when the flag was "a" (append). There are other flag values that also mean append, and should look up the current size when used.

fix: added extra flag values that need size

---

lib/RollingFileWriteStream.js
test/DateRollingFileStream-test.js
test/RollingFileStream-test.js

Rearranged functions in `RollingFileWriteStream` so that they are in the order they get used, which should make it easier to read the code from top to bottom. Changed a lot of test code which was using string concatenation for file paths to use `path.join`.

Tidying up

---

package.json
test/DateRollingFileStream-test.js
test/RollingFileStream-test.js
test/RollingFileWriteStream-test.js

I've replaced the async lib with async/await in the tests as well. It made them easier to understand.

Remove async lib from dev dependencies

---

lib/RollingFileWriteStream.js
package.json
test/DateRollingFileStream-test.js
test/RollingFileStream-test.js
test/RollingFileWriteStream-test.js
test/fileNameFormatter-test.js

Windows does not like it when you don't close streams properly, resulting in locked files and weird errors. Most of the changes in here fix that, and also the paths expected by the tests.
Also added a `_final` method implementation because we weren't closing the underlying stream sometimes.

chore: added _final method, fixed tests for windows

---

lib/RollingFileWriteStream.js
lib/moveAndMaybeCompressFile.js
test/moveAndMaybeCompressFile-test.js

This should make things more reliable in Windows, when another process has the source file open. You get an EBUSY error when you try to delete files that something else is reading, so this code falls back to doing a copy and truncate if the move fails.

fix: fallback to copy+truncate on error

---

lib/RollingFileWriteStream.js
test/RollingFileWriteStream-test.js

This should fix the problem of unhandled promise rejections during cleanup of old files (mostly a windows problem, I think). See https://github.com/log4js-node/log4js-node/issues/959 for details.

fix: catch unlink errors during cleanup

---

lib/fileNameParser.js
test/fileNameParser-test.js

Related to issue #60 . Files that :
- have  a "base name" that is not matching the template,
- but were ending by a suitable timestamp
were taken into consideration for the log rolling.

fix: all files ending by a timestamp were validated

---

lib/RollingFileWriteStream.js
lib/moveAndMaybeCompressFile.js
package.json
test/moveAndMaybeCompressFile-test.js

Related to https://github.com/log4js-node/log4js-node/issues/1043

feat: enable to set mode of the compressed archive

---

README.md
lib/DateRollingFileStream.js
lib/RollingFileStream.js
lib/RollingFileWriteStream.js
test/DateRollingFileStream-test.js
test/RollingFileStream-test.js
test/RollingFileWriteStream-test.js

Fixes #59
**Public APIs:**
- `RollingFileStream`
`backups` excludes the hot file (original behavior retained)
<table><tr><th width="180">backups=0</th><th width="180">backups=1 (default)</th><th width="180">backups=2</th><th width="180">backups=3</th></tr><tr><td>filename.log<br><strike>filename.log.1</strike><br>&nbsp;<br>&nbsp;</td><td>filename.log<br>filename.log.1<br>&nbsp;<br>&nbsp;</td><td>filename.log<br>filename.log.1<br>filename.log.2<br>&nbsp;</td><td>filename.log<br>filename.log.1<br>filename.log.2<br>filename.log.3</td></tr></table>
- `DateRollingFileStream`
`daysToKeep` excludes the hot file (original behavior retained)
<table><tr><th width="180">daysToKeep=0 <strike>(default)</strike></th><th width="180">daysToKeep=1 <font style="color:green">(default)</font></th><th …

fix: allow for zero backups and zero daysToKeep

---

lib/DateRollingFileStream.js
test/DateRollingFileStream-test.js

fix: extra separator

---

README.md
lib/DateRollingFileStream.js
lib/RollingFileStream.js
lib/RollingFileWriteStream.js
test/DateRollingFileStream-test.js
test/RollingFileStream-test.js

Fixes https://github.com/log4js-node/log4js-node/issues/1080, Fixes https://github.com/log4js-node/log4js-node/issues/1035

fix: using options.numBackups instead of options.daysToKeep

---

package-lock.json
package.json

Path: nyc [dev] > istanbul-lib-instrument > @babel/core > json5 > minimist
* Fix: Removed dependence on minimist to patch CVE-2021-44906. (https://github.com/json5/json5/issues/266)

chore(dep): updated dependencies

---

lib/RollingFileWriteStream.js
lib/moveAndMaybeCompressFile.js
test/fs-extra-test.js

Fixes https://github.com/log4js-node/log4js-node/issues/1225

chore(dep): temporary fix for fs-extra issue (to be reverted when fs-extra patches it)

---

lib/moveAndMaybeCompressFile.js
test/moveAndMaybeCompressFile-test.js

chore(refactor): use writeStream.destroy() instead

---

lib/RollingFileWriteStream.js
test/RollingFileStream-test.js
test/RollingFileWriteStream-test.js

Reverts log4js-node/streamroller#129

Revert "chore(fix): maxSize=0 means no rolling"

---

lib/RollingFileWriteStream.js
lib/moveAndMaybeCompressFile.js
test/RollingFileWriteStream-test.js

1. file cannot be a directory
2. throws EISDIR, EROFS, EACCES synchronously

fix: better file validation

---

lib/RollingFileWriteStream.js

1. `~` in `~/` or `~\` will be expanded to `os.homedir()`
(`~` and `~filename` unaffected as these are valid filenames)

feat: tilde expansion for filename

---

lib/RollingFileWriteStream.js

Strangely, `fs.appendFileSync` uses `flag` but `fs.createWriteStream` uses `flags`.
It's somewhat inconsistent throughout the Node.js documentation:
https://nodejs.org/api/fs.html

fix: fs.appendFileSync should use flag instead of flags

---

.github/workflows/node.js.yml

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

ci: replaced deprecated github set-output

---

lib/RollingFileWriteStream.js
test/RollingFileWriteStream-test.js

Fixes #164
1. `~` in `~/` or `~\` will be expanded to `os.homedir()`
(`~` and `~filename` unaffected as these are valid filenames)

fix: tilde expansion for windows
